// Curated word lists for the mini-games. Not exhaustive dictionaries —
// picked for decent everyday-word coverage without bundling a huge corpus.

// Secret-word pool for Wordle Together (never sent to the client).
const WORDLE_WORDS = [
  'apple', 'beach', 'candy', 'dance', 'eagle', 'faith', 'grace', 'heart',
  'ivory', 'jolly', 'kudos', 'lemon', 'magic', 'noble', 'ocean', 'peace',
  'quiet', 'river', 'smile', 'trust', 'unity', 'value', 'wafer', 'youth',
  'zesty', 'amber', 'bliss', 'charm', 'dream', 'ember', 'flame', 'glory',
  'honey', 'inbox', 'joker', 'kneel', 'light', 'mango', 'night', 'olive',
  'pearl', 'quilt', 'radio', 'sunny', 'tiger', 'ultra', 'vivid', 'water',
  'xenon', 'yield', 'zebra', 'angel', 'brave', 'crisp', 'dizzy', 'early',
  'fable', 'ghost', 'happy', 'index', 'jumpy', 'karma', 'lucky', 'merry',
  'north', 'oasis', 'panda', 'quirk', 'reach', 'shine', 'topaz', 'unite',
  'vigor', 'windy', 'yacht', 'zonal', 'adore', 'blush', 'cabin', 'delta',
  'exact', 'flint', 'gleam', 'humor', 'idyll', 'joint', 'knack', 'level',
  'mirth', 'nurse', 'onset', 'plaza', 'quest', 'roast', 'salty', 'total',
  'usual', 'venus', 'wheat', 'xerox', 'yummy', 'zippy', 'anime', 'blaze',
  'crown', 'dwell', 'eight', 'frost', 'giant', 'hover', 'input', 'juicy',
  'knock', 'lemur', 'mocha', 'nifty', 'orbit', 'plush', 'quota', 'ridge',
  'shape', 'trace', 'urban', 'vault', 'whisk', 'yodel', 'amuse', 'blend',
  'chase', 'draft', 'enjoy', 'fancy', 'grape', 'hobby', 'ideal', 'jelly',
  'kayak', 'later', 'siren', 'outer', 'pizza', 'query', 'rally',
  'stone', 'tulip', 'usher', 'vowel', 'wrist', 'shard', 'amity', 'bacon',
  'cliff', 'dandy', 'ethic', 'flair', 'globe', 'hazel', 'islet', 'jumbo',
  'knife', 'lodge', 'moist', 'nudge', 'oxide', 'plumb', 'quake', 'realm',
  'scent', 'thumb', 'union', 'valid', 'wonky', 'aroma', 'basil',
  'coral', 'debut', 'fiber', 'grain', 'hinge', 'issue', 'jaunt', 'karat',
  'lunar', 'metro', 'nomad', 'opera', 'perky', 'quart', 'robin', 'sheep',
  'tempo', 'vapor', 'witty',
].filter((w) => /^[a-z]{5}$/.test(w));

// Broader wordlist for Letter Hunt validation (3-7 letters, common words).
const DICTIONARY = [
  'ace', 'act', 'add', 'age', 'aid', 'aim', 'air', 'ale', 'all', 'and',
  'ant', 'any', 'ape', 'arc', 'are', 'arm', 'art', 'ash', 'ask', 'ate',
  'awe', 'axe', 'bad', 'bag', 'ban', 'bar', 'bat', 'bay', 'bed', 'bee',
  'beg', 'bet', 'bid', 'big', 'bin', 'bit', 'boa', 'bog', 'bow', 'box',
  'boy', 'bud', 'bug', 'bun', 'bus', 'but', 'buy', 'cab', 'can', 'cap',
  'car', 'cat', 'caw', 'cob', 'cod', 'cog', 'con', 'cop', 'cot', 'cow',
  'cry', 'cub', 'cup', 'cur', 'cut', 'dab', 'dad', 'dam', 'day', 'den',
  'dew', 'did', 'dig', 'dim', 'din', 'dip', 'doe', 'dog', 'dot', 'dry',
  'dub', 'dud', 'due', 'dug', 'dun', 'ear', 'eat', 'ebb', 'eel', 'egg',
  'ego', 'elf', 'elk', 'elm', 'end', 'era', 'eve', 'ewe', 'eye', 'fad',
  'fan', 'far', 'fat', 'fed', 'fee', 'fen', 'few', 'fig', 'fin', 'fit',
  'fix', 'flu', 'fly', 'fog', 'for', 'fox', 'fry', 'fun', 'fur', 'gab',
  'gag', 'gap', 'gas', 'gel', 'gem', 'get', 'gig', 'gin', 'got', 'gum',
  'gun', 'gut', 'guy', 'gym', 'had', 'ham', 'has', 'hat', 'hay', 'hem',
  'hen', 'her', 'hid', 'him', 'hip', 'his', 'hit', 'hog', 'hop', 'hot',
  'how', 'hub', 'hue', 'hug', 'hum', 'hut', 'ice', 'ill', 'ink', 'inn',
  'ion', 'ire', 'irk', 'its', 'ivy', 'jab', 'jam', 'jar', 'jaw', 'jay',
  'jet', 'jig', 'job', 'jog', 'jot', 'joy', 'jug', 'jut', 'keg', 'ken',
  'key', 'kid', 'kin', 'kit', 'lab', 'lad', 'lag', 'lap', 'law', 'lax',
  'lay', 'led', 'leg', 'let', 'lid', 'lie', 'lip', 'lit', 'log', 'lot',
  'low', 'mad', 'man', 'map', 'mat', 'may', 'men', 'met', 'mix', 'mob',
  'mod', 'mom', 'mop', 'mud', 'mug', 'nag', 'nap', 'net', 'new', 'nib',
  'nil', 'nip', 'nit', 'nod', 'nor', 'not', 'now', 'nun', 'nut', 'oak',
  'oar', 'oat', 'odd', 'ode', 'off', 'oil', 'old', 'one', 'orb', 'ore',
  'our', 'out', 'owe', 'owl', 'own', 'pad', 'pal', 'pan', 'par', 'pat',
  'paw', 'pay', 'pea', 'pen', 'pet', 'pie', 'pig', 'pin', 'pit', 'ply',
  'pod', 'pot', 'pry', 'pub', 'pug', 'pun', 'pup', 'put', 'rag', 'ram',
  'ran', 'rap', 'rat', 'raw', 'ray', 'red', 'rib', 'rid', 'rig', 'rim',
  'rip', 'rob', 'rod', 'rot', 'row', 'rub', 'rug', 'rum', 'run', 'rut',
  'rye', 'sad', 'sap', 'sat', 'saw', 'say', 'sea', 'set', 'sew', 'she',
  'shy', 'sin', 'sip', 'sir', 'sit', 'six', 'ski', 'sky', 'sly', 'sob',
  'sod', 'son', 'sow', 'soy', 'spa', 'spy', 'sty', 'sub', 'sum', 'sun',
  'tab', 'tag', 'tan', 'tap', 'tar', 'tax', 'tea', 'ten', 'the', 'tie',
  'tin', 'tip', 'toe', 'ton', 'too', 'top', 'tot', 'toy', 'try', 'tub',
  'tug', 'two', 'urn', 'use', 'van', 'vat', 'vet', 'via', 'vow', 'wag',
  'war', 'was', 'wax', 'way', 'web', 'wed', 'wet', 'who', 'why', 'wig',
  'win', 'wit', 'woe', 'wok', 'won', 'wow', 'yak', 'yam', 'yes', 'yet',
  'yew', 'you', 'zap', 'zig', 'zip', 'zoo',
  'able', 'acid', 'aged', 'also', 'area', 'army', 'atom', 'aunt', 'auto',
  'away', 'baby', 'back', 'bake', 'ball', 'band', 'bank', 'barn', 'base',
  'bath', 'bead', 'beam', 'bean', 'bear', 'beat', 'been', 'beer', 'bell',
  'belt', 'bend', 'best', 'bike', 'bird', 'bite', 'blue', 'boat', 'body',
  'bold', 'bolt', 'bond', 'bone', 'book', 'boot', 'born', 'boss', 'both',
  'bowl', 'bulk', 'bull', 'burn', 'bush', 'busy', 'cafe', 'cage', 'cake',
  'call', 'calm', 'camp', 'card', 'care', 'cart', 'case', 'cash', 'cast',
  'cave', 'cell', 'chat', 'chef', 'chip', 'city', 'clan', 'claw', 'clay',
  'club', 'coal', 'coat', 'code', 'coin', 'cold', 'cone', 'cook', 'cool',
  'cope', 'copy', 'cord', 'core', 'cork', 'corn', 'cost', 'crab', 'crew',
  'crop', 'dark', 'dart', 'dash', 'data', 'date', 'dawn', 'days', 'dead',
  'deal', 'dean', 'dear', 'debt', 'deck', 'deed', 'deep', 'deer', 'dent',
  'desk', 'dial', 'dice', 'diet', 'dine', 'dirt', 'dish', 'dive', 'dock',
  'does', 'doll', 'done', 'door', 'dose', 'down', 'drag', 'draw', 'drop',
  'drum', 'dual', 'duck', 'dude', 'duke', 'dull', 'dune', 'dusk', 'dust',
  'duty', 'each', 'earn', 'ease', 'east', 'easy', 'edge', 'edit', 'else',
  'even', 'ever', 'evil', 'exit', 'face', 'fact', 'fade', 'fail', 'fair',
  'fake', 'fall', 'fame', 'farm', 'fast', 'fate', 'fear', 'feat', 'feed',
  'feel', 'feet', 'fell', 'felt', 'file', 'fill', 'film', 'find', 'fine',
  'fire', 'firm', 'fish', 'fist', 'five', 'flag', 'flat', 'flee', 'flew',
  'flip', 'flow', 'foam', 'fold', 'folk', 'font', 'food', 'fool', 'foot',
  'ford', 'fork', 'form', 'fort', 'four', 'free', 'fuel', 'full', 'fund',
  'fury', 'fuse', 'gain', 'game', 'gasp', 'gate', 'gaze', 'gear', 'gift',
  'girl', 'give', 'glad', 'glow', 'glue', 'goal', 'goat', 'gold', 'golf',
  'gone', 'good', 'gown', 'grab', 'gray', 'grew', 'grey', 'grid', 'grin',
  'grip', 'grow', 'gulf', 'gulp', 'guru', 'hail', 'hair', 'half', 'hall',
  'halt', 'hand', 'hang', 'hard', 'harm', 'hate', 'have', 'hawk', 'haze',
  'head', 'heal', 'heap', 'hear', 'heat', 'heel', 'held', 'hell', 'helm',
  'help', 'herb', 'herd', 'here', 'hero', 'hide', 'high', 'hill', 'hint',
  'hire', 'hive', 'hold', 'hole', 'holy', 'home', 'hood', 'hoof', 'hook',
  'hope', 'horn', 'host', 'hour', 'huge', 'hull', 'hunt', 'hurt', 'hush',
  'icon', 'idea', 'idle', 'inch', 'into', 'iron', 'item', 'jazz', 'join',
  'joke', 'jump', 'jury', 'just', 'keen', 'keep', 'kick', 'kill', 'kind',
  'king', 'kiss', 'kite', 'knee', 'knew', 'knit', 'know', 'lace', 'lack',
  'lady', 'lake', 'lamb', 'lamp', 'land', 'lane', 'lark', 'last', 'late',
  'lawn', 'lazy', 'lead', 'leaf', 'lean', 'leap', 'left', 'lend', 'lens',
  'lent', 'less', 'life', 'lift', 'like', 'lily', 'lime', 'line', 'link',
  'lion', 'list', 'live', 'load', 'loaf', 'loan', 'lock', 'loft', 'lone',
  'long', 'look', 'loop', 'lord', 'lose', 'loss', 'lost', 'loud', 'love',
  'luck', 'lump', 'lung', 'made', 'mail', 'main', 'make', 'male', 'mall',
  'many', 'maps', 'mark', 'mask', 'mass', 'mate', 'meal', 'mean', 'meat',
  'meet', 'melt', 'menu', 'mesh', 'mess', 'mice', 'mild', 'mile', 'milk',
  'mind', 'mine', 'mint', 'miss', 'mist', 'moan', 'mode', 'mold', 'mole',
  'monk', 'mood', 'moon', 'more', 'moss', 'most', 'moth', 'move', 'much',
  'muck', 'mule', 'must', 'myth', 'nail', 'name', 'near', 'neat', 'neck',
  'need', 'nest', 'news', 'next', 'nice', 'nine', 'node', 'none', 'noon',
  'norm', 'nose', 'note', 'noun', 'nude', 'numb', 'oath', 'oats', 'obey',
  'okay', 'omen', 'once', 'only', 'onto', 'open', 'oral', 'oven', 'over',
  'pace', 'pack', 'page', 'paid', 'pain', 'pair', 'pale', 'palm', 'pang',
  'park', 'part', 'pass', 'past', 'path', 'peak', 'pear', 'peel', 'peer',
  'pest', 'pick', 'pier', 'pike', 'pile', 'pill', 'pine', 'pink', 'pint',
  'pipe', 'pity', 'plan', 'play', 'plot', 'plow', 'plum', 'plus', 'poem',
  'poet', 'pole', 'poll', 'pond', 'pool', 'poor', 'pop', 'pork', 'port',
  'pose', 'post', 'pour', 'pray', 'prep', 'prey', 'prod', 'prop', 'pull',
  'pulp', 'pump', 'pure', 'push', 'quiz', 'race', 'rack', 'rage', 'raid',
  'rail', 'rain', 'rank', 'rare', 'rate', 'rays', 'read', 'real', 'reap',
  'rear', 'rely', 'rent', 'rest', 'rice', 'rich', 'ride', 'ring', 'riot',
  'ripe', 'rise', 'risk', 'road', 'roar', 'robe', 'rock', 'rode', 'role',
  'roll', 'roof', 'room', 'root', 'rope', 'rose', 'rosy', 'ruin', 'rule',
  'runs', 'rush', 'rust', 'sack', 'safe', 'sail', 'sake', 'sale', 'salt',
  'same', 'sand', 'sane', 'save', 'scan', 'seal', 'seat', 'seed', 'seek',
  'seem', 'seen', 'self', 'sell', 'send', 'sent', 'shed', 'shelf', 'shift',
  'ship', 'shoe', 'shop', 'shot', 'show', 'shut', 'sick', 'side', 'sign',
  'silk', 'sing', 'sink', 'site', 'size', 'skew', 'skin', 'skip', 'slab',
  'slap', 'sled', 'slid', 'slim', 'slip', 'slot', 'slow', 'snap', 'snow',
  'soap', 'soar', 'sock', 'soda', 'sofa', 'soft', 'soil', 'sold', 'sole',
  'some', 'song', 'soon', 'sore', 'sort', 'soul', 'soup', 'sour', 'span',
  'spin', 'spot', 'spun', 'spur', 'star', 'stay', 'stem', 'step', 'stew',
  'stir', 'stop', 'stow', 'stub', 'such', 'suit', 'sung', 'sunk', 'sure',
  'swan', 'swap', 'swim', 'tack', 'tail', 'take', 'tale', 'talk', 'tall',
  'tame', 'tank', 'tape', 'task', 'taxi', 'team', 'tear', 'tell', 'tend',
  'tent', 'term', 'test', 'text', 'than', 'that', 'thaw', 'them', 'then',
  'they', 'thin', 'this', 'thud', 'thus', 'tick', 'tide', 'tidy', 'tile',
  'till', 'tilt', 'time', 'tiny', 'tire', 'toad', 'told', 'toll', 'tomb',
  'tone', 'tons', 'took', 'tool', 'toot', 'tore', 'torn', 'tour', 'town',
  'trap', 'tray', 'tree', 'trek', 'trim', 'trip', 'trot', 'true', 'tuba',
  'tube', 'tuck', 'tuna', 'tune', 'turf', 'turn', 'twin', 'type', 'ugly',
  'undo', 'unit', 'upon', 'urge', 'used', 'user', 'vain', 'vast', 'veil',
  'vein', 'verb', 'very', 'vest', 'view', 'vine', 'visa', 'void', 'volt',
  'vote', 'wade', 'wage', 'wait', 'wake', 'walk', 'wall', 'wand', 'want',
  'ward', 'warm', 'warn', 'wash', 'wave', 'wavy', 'ways', 'weak', 'wear',
  'weed', 'week', 'well', 'went', 'were', 'west', 'what', 'when', 'whip',
  'whom', 'wick', 'wide', 'wife', 'wild', 'will', 'wind', 'wine', 'wing',
  'wink', 'wire', 'wise', 'wish', 'with', 'wolf', 'wood', 'wool', 'word',
  'wore', 'work', 'worm', 'worn', 'wrap', 'yard', 'yarn', 'year', 'yell',
  'yoga', 'yolk', 'zero', 'zest', 'zone',
  'apple', 'beach', 'brain', 'bread', 'bring', 'brown', 'brush', 'catch',
  'chair', 'chalk', 'charm', 'chest', 'chill', 'claim', 'class', 'clean',
  'clear', 'climb', 'clock', 'close', 'cloud', 'coach', 'coast', 'could',
  'count', 'court', 'cover', 'crack', 'craft', 'crash', 'cream', 'crowd',
  'crown', 'dance', 'dozen', 'dream', 'dress', 'drink', 'drive', 'earth',
  'eight', 'empty', 'enjoy', 'enter', 'equal', 'every', 'field', 'fight',
  'first', 'flame', 'floor', 'flour', 'focus', 'force', 'forth', 'found',
  'frame', 'fresh', 'front', 'fruit', 'globe', 'grace', 'grade', 'grand',
  'grant', 'grass', 'great', 'green', 'gross', 'group', 'guard', 'guess',
  'guest', 'guide', 'happy', 'heart', 'heavy', 'horse', 'hotel', 'house',
  'human', 'ideal', 'image', 'issue', 'judge', 'juice', 'known', 'label',
  'laugh', 'layer', 'learn', 'least', 'leave', 'level', 'light', 'limit',
  'local', 'lucky', 'lunch', 'match', 'maybe', 'mayor', 'medal', 'media',
  'metal', 'meter', 'might', 'money', 'month', 'moral', 'motor', 'mount',
  'mouse', 'mouth', 'movie', 'music', 'never', 'night', 'noise', 'north',
  'novel', 'nurse', 'offer', 'often', 'order', 'other', 'ought', 'owner',
  'paint', 'panel', 'paper', 'party', 'peace', 'phase', 'phone', 'photo',
  'piano', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant',
  'plate', 'point', 'pound', 'power', 'press', 'price', 'pride', 'prime',
  'print', 'prize', 'proof', 'proud', 'prove', 'queen', 'quick', 'quiet',
  'quite', 'radio', 'raise', 'range', 'rapid', 'reach', 'ready', 'refer',
  'right', 'river', 'round', 'route', 'royal', 'rural', 'scale', 'scene',
  'scope', 'score', 'sense', 'serve', 'seven', 'shade', 'shake', 'shall',
  'shape', 'share', 'sharp', 'sheep', 'sheet', 'shelf', 'shell', 'shine',
  'shirt', 'shock', 'shoot', 'shore', 'short', 'sight', 'since', 'skill',
  'sleep', 'slide', 'small', 'smart', 'smell', 'smile', 'smoke', 'snake',
  'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak',
  'speed', 'spend', 'spent', 'spirit', 'split', 'sport', 'staff', 'stage',
  'stair', 'stand', 'stark', 'start', 'state', 'stay', 'steam', 'steel',
  'steep', 'stick', 'still', 'stock', 'stone', 'store', 'storm', 'story',
  'stove', 'straw', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar',
  'sweet', 'swept', 'swing', 'table', 'taken', 'taste', 'teach', 'tears',
  'tempo', 'tends', 'thank', 'their', 'theme', 'there', 'these', 'thick',
  'thing', 'think', 'third', 'those', 'three', 'threw', 'throw', 'thumb',
  'tight', 'timer', 'tired', 'title', 'today', 'topic', 'total', 'touch',
  'tough', 'tower', 'track', 'trade', 'trail', 'train', 'treat', 'trend',
  'trial', 'tribe', 'trick', 'tried', 'tries', 'truck', 'truly', 'trust',
  'truth', 'twice', 'uncle', 'under', 'union', 'unity', 'until', 'upper',
  'urban', 'usual', 'valid', 'value', 'video', 'visit', 'voice', 'waste',
  'watch', 'water', 'wheel', 'where', 'which', 'while', 'white', 'whole',
  'whose', 'woman', 'women', 'world', 'worry', 'worth', 'would', 'write',
  'wrong', 'yield', 'young', 'youth',
];

module.exports = { WORDLE_WORDS, DICTIONARY };
